// <auto-generated />
using System;
using BloodDoner.Mvc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BloodDoner.Mvc.Migrations
{
    [DbContext(typeof(BloodDonerDbContext))]
    [Migration("20250702155514_InitialDbCreationWithSeedData")]
    partial class InitialDbCreationWithSeedData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BloodDoner.Mvc.Models.BloodDonerEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BloodGroup")
                        .HasColumnType("int");

                    b.Property<string>("ContactNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("DateofBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastDonationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Weight")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.ToTable("BloodDoners");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Chittagong",
                            BloodGroup = 2,
                            ContactNumber = "957579758975",
                            DateofBirth = new DateTime(1990, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "saima@gmail.com",
                            FullName = "Sanjida Afrin",
                            LastDonationDate = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfilePicture = "profiles/Screenshot (178).png",
                            Weight = 60f
                        },
                        new
                        {
                            Id = 2,
                            Address = "Dhaka",
                            BloodGroup = 0,
                            ContactNumber = "123747428778",
                            DateofBirth = new DateTime(2005, 5, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "saima@gmail.com",
                            FullName = "Saima khan",
                            LastDonationDate = new DateTime(2025, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ProfilePicture = "profiles/Screenshot (178).png",
                            Weight = 90f
                        });
                });

            modelBuilder.Entity("BloodDoner.Mvc.Models.Donation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BloodDonerEntityId")
                        .HasColumnType("int");

                    b.Property<int>("BloodDonerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DonationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("BloodDonerEntityId");

                    b.ToTable("Donations");
                });

            modelBuilder.Entity("BloodDoner.Mvc.Models.Donation", b =>
                {
                    b.HasOne("BloodDoner.Mvc.Models.BloodDonerEntity", null)
                        .WithMany("Donations")
                        .HasForeignKey("BloodDonerEntityId");
                });

            modelBuilder.Entity("BloodDoner.Mvc.Models.BloodDonerEntity", b =>
                {
                    b.Navigation("Donations");
                });
#pragma warning restore 612, 618
        }
    }
}
